IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'PARQUE_CARBONES')
BEGIN
    CREATE DATABASE PARQUE_CARBONES;
END
GO -- FIN LOTE SINO NO VA EL USE

USE PARQUE_CARBONES;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Camiones')
BEGIN
    CREATE TABLE Camiones(
        Id_Camion INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
        Matricula VARCHAR(15) UNIQUE NOT NULL,--TAMAÑO 15 PARA SU IMPLEMENTACIÓN EN CUALQUIER PAÍS (MALASIA TIENE 15 CARACTERES DE MATRÍCULA)
        Empresa VARCHAR(70),
        Permitido BIT NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Camioneros')
BEGIN
    CREATE TABLE Camioneros(
        Id_Camionero INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
        Nombre VARCHAR(30) NOT NULL,
        Apellidos VARCHAR(60) NOT NULL,
        Documento_Identidad VARCHAR(15) NOT NULL,--EL DOCUMENTO DE IDENTIDAD CON MÁS CARACTERES ES INDIA CON 15
        Pais VARCHAR(20) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Entradas')
BEGIN
    CREATE TABLE Entradas(
        Id_Entrada INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
        Fecha_Entrada DATETIME NOT NULL,
        Foto VARBINARY(MAX),
        Peso DECIMAL(30, 10) NOT NULL,
        Id_Camionero INT NOT NULL,
        Id_Camion INT NOT NULL,
        FOREIGN KEY (Id_Camion) REFERENCES Camiones(Id_Camion),
        FOREIGN KEY (Id_Camionero) REFERENCES Camioneros(Id_Camionero)
    );
END
